---
development: &development
  secret_key_base:      <%= 'x' * 30 %>

  github_app_name:      <%= ENV['GITHUB_APP_NAME']%>
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

  google_maps_api_key:  <%= ENV['GOOGLE_MAPS_API_KEY'] %>

production:
  <<: *development
  secret_key_base:      <%= ENV['SECRET_KEY_BASE'] %>

review:
  <<: *development

test:
  <<: *development
  github_app_name: 'wdt-auth-test'
